// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Nj2InXzOg6_6rZNp1uqjLJONY1UOCls',
    appId: '1:787676448167:web:97ca9943145bb4cf502282',
    messagingSenderId: '787676448167',
    projectId: 'food-acdf7',
    authDomain: 'food-acdf7.firebaseapp.com',
    storageBucket: 'food-acdf7.firebasestorage.app',
    measurementId: 'G-MH6838L8CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATaxGvLLaRIWN1LHOHpjrY9OlulrtY5dE',
    appId: '1:787676448167:android:d049b2fb75fdb120502282',
    messagingSenderId: '787676448167',
    projectId: 'food-acdf7',
    storageBucket: 'food-acdf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAQkCC6cRbr-KW5GAPyFNUGCgBV2wZHE',
    appId: '1:787676448167:ios:8794b7493c673fed502282',
    messagingSenderId: '787676448167',
    projectId: 'food-acdf7',
    storageBucket: 'food-acdf7.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaAQkCC6cRbr-KW5GAPyFNUGCgBV2wZHE',
    appId: '1:787676448167:ios:8794b7493c673fed502282',
    messagingSenderId: '787676448167',
    projectId: 'food-acdf7',
    storageBucket: 'food-acdf7.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Nj2InXzOg6_6rZNp1uqjLJONY1UOCls',
    appId: '1:787676448167:web:e7af2ed7db855572502282',
    messagingSenderId: '787676448167',
    projectId: 'food-acdf7',
    authDomain: 'food-acdf7.firebaseapp.com',
    storageBucket: 'food-acdf7.firebasestorage.app',
    measurementId: 'G-X0F9TFTC0W',
  );
}
